### ISSUE TITLE
Exploits

### ISSUE THREAD

**Issue by kolya009** [bazad/physmem#2]
(CVE-2017-2494), (CVE-2017-2546) -   memory corruption exist in the Kernel
component that allow a local attacker to gain kernel-level privileges

 (CVE-2017-2501) A local privilege escalation vulnerability exists in the Kernel component due to a race condition

(CVE-2017-2533) A race condition exists in the DiskArbitration feature that allow a local attacker to gain system-level privileges

(CVE-2017-2537), (CVE-2017-2548) Multiple memory corruption issues exist in the
WindowServer component that allow a local attacker to execute arbitrary code with system-level privileges

Would any of these work? Or is there a certain type of exploit(s) you need?

**Comment by bazad** [comment]
Any of these vulnerabilities could probably be developed into a full exploit. However, the purpose of physmem isn't to exploit any old bug to get root; the purpose of physmem is to demonstrate a very simple and reliable exploitation technique on macOS facilitated by a very particular kind of vulnerability.

The reason physmem supported both CVE-2016-1825 and CVE-2016-7067 is that they were really the same bug: an unprivileged write to the protected IOUserClientClass registry property. Because of this, the exploit code for both is the same. I don't plan to update physmem unless another version of this bug vulnerable to the same exploit technique is discovered, which is unlikely.
